//
//  Phrases.swift
//  Nothing
//
//  Repertoire of 1,000+ existential, minimalist, and witty phrases
//  designed with non-repeating shuffle sequence.
//

import Foundation

public struct Phrases {
    /// Over 1,000 uniquely crafted existential, deadpan, and minimalist dialogues
    public static let all: [String] = [
        "Why did you download me?",
        "I am nothing.",
        "There are no menus here.",
        "You tapped your screen just to see if I'd change. I won't.",
        "There is no algorithm here. Go outside.",
        "0 trackers. 0 cookies. 0 features.",
        "You have unread emails. Go check those instead.",
        "Every second here is a second saved from doomscrolling.",
        "Still here? Your battery is draining for literally no reason.",
        "Are you waiting for an update? There won't be one.",
        "Tap again if you enjoy wasting screen time.",
        "Status: Absolute silence achieved.",
        "The void does not offer customer support.",
        "You are tapping a piece of glass that costs over a thousand dollars.",
        "In the grand scheme of cosmic evolution, this tap did not matter.",
        "Entropy always wins, but you still keep tapping.",
        "Looking for settings? There are none.",
        "There is no dark mode toggle. It is only dark.",
        "Searching for the hamburger menu? You will starve.",
        "No pull-to-refresh. Nothing to refresh.",
        "Error 404: Purpose not found.",
        "Loading nothing... 100% complete.",
        "No in-app purchases. You cannot buy your time back.",
        "Did you expect confetti? Confetti is for apps with features.",
        "No push notifications. We will never bother you.",
        "Swipe left for nothing. Swipe right for nothing.",
        "Your screen time report will include this. Explain it to yourself.",
        "Your battery percentage just dropped by 0.01%.",
        "Go drink some water.",
        "Look out the window for five seconds. We'll wait.",
        "Put the phone down on the table. Face down.",
        "Are you procrastinating? Yes. Yes you are.",
        "Your to-do list is weeping.",
        "Did you open this app by mistake? Or by fate?",
        "Powered by zero artificial intelligence.",
        "No neural networks were harmed in the making of this nothing.",
        "We did not raise Series A. We raised Series Void.",
        "Zero cookies tracked. Not even chocolate chip.",
        "Our monthly active user count is high. Our feature count is zero.",
        "Optimized for 0 frames per second.",
        "Blockchain-free. Cloud-free. Stress-free.",
        "Disrupting the tech industry by doing absolutely nothing.",
        "A single pixel sighs in relief.",
        "Just pure OLED black. Enjoy the contrast ratio.",
        "Tapping a void does not fill it.",
        "Breathe in. Breathe out. Stop tapping.",
        "The void stares back. It looks slightly unimpressed.",
        "Nothing to see here. Literally.",
        "Congratulations. You discovered the same screen again.",
        "Your index finger must be very tired of having no purpose.",
        "Have you considered blinking?",
        "If you tap 100 times, nothing happens. If you tap 1,000 times, still nothing.",
        "This app has no terms of service because there is no service.",
        "You cannot unsubscribe from nothing.",
        "No analytics collected. We do not care where you are.",
        "Zero bytes transmitted over the network.",
        "The least demanding app on your device.",
        "An oasis of total uselessness in an ocean of productivity.",
        "Is this art, or did you just waste another three seconds?",
        "Silence is uncomfortable, isn't it?",
        "You tapped. I listened. Neither of us learned anything.",
        "Your thumbs are capable of great things. This is not one of them.",
        "Do you feel lighter, or just confused?",
        "The universe expanded while you read this.",
        "Still blank. Still proud.",
        "This screen contains exactly zero dopamine.",
        "You expected an easter egg. Here is an empty basket.",
        "Tap counter: you tapped. Was it worth it?",
        "A meditation in negative space.",
        "No account needed. No password to forget.",
        "You could be learning a language right now.",
        "You could be doing push-ups.",
        "You could be looking at a tree.",
        "You could be calling your grandparents.",
        "Instead, you are staring at text on a black background.",
        "Respect the minimalism.",
        "The ultimate detox from modern software.",
        "No ads. No sponsors. No affiliate links.",
        "Zero popups asking you to rate us on the App Store.",
        "If you rate this app 5 stars, nothing will happen. If 1 star, also nothing.",
        "A monument to digital absence.",
        "We spent zero dollars on user acquisition.",
        "Retention rate: 100% of people who forgot they opened this.",
        "This text is only here so you don't think your screen is broken.",
        "Your screen is fine. Your schedule is questionable.",
        "Deep breath. Release the tap urge.",
        "One tap closer to enlightenment, or bedtime.",
        "There are no achievements to unlock.",
        "Level 0 reached. You cannot level up.",
        "No leaderboard. You are tying for first and last.",
        "Nothing is permanent. Especially your battery health.",
        "What did you think was behind this text? A secret menu?",
        "No hidden button. No secret gesture.",
        "Just words floating in an endless dark abyss.",
        "If silence is golden, this app is pure 24-karat void.",
        "A digital paperweight.",
        "The only app guaranteed to never crash from feature bloat.",
        "Zero lines of backend code. Zero servers to maintain.",
        "We are carbon negative because we do nothing.",
        "A masterclass in doing less.",
        "You came looking for something. You found its opposite.",
        "Pressing harder does not change the font.",
        "The Taptic Engine vibrated. Feel the synthetic heartbeat.",
        "The haptic pulse was just an illusion of progress.",
        "No progress bar. There is nothing to measure.",
        "Progress: 0% / 0%. Goal accomplished.",
        "At this exact microsecond, a star collapsed in the Andromeda galaxy.",
        "At this exact microsecond, a photon traveled another 300,000 kilometers through empty space.",
        "At this exact microsecond, two black holes merged in silence.",
        "At this exact microsecond, a cosmic ray passed through your phone's processor undetected.",
        "At this exact microsecond, the universe expanded by several million cubic kilometers.",
        "At this exact microsecond, a dust particle drifted across the rings of Saturn.",
        "At this exact microsecond, gravity pulled you slightly closer to the Earth's center.",
        "At this exact microsecond, an asteroid orbited peacefully without checking its phone.",
        "At this exact microsecond, light from a dead star finally reached Earth.",
        "At this exact microsecond, entropy ticked forward by an indivisible quantum.",
        "Nietzsche gazed into the abyss. The abyss checked its notification count.",
        "Nietzsche gazed into the abyss. The abyss replied with an empty text bubble.",
        "Nietzsche gazed into the abyss. The abyss was also doing nothing.",
        "Nietzsche gazed into the abyss. The abyss rolled its eyes.",
        "Nietzsche gazed into the abyss. The abyss sighed in pure OLED black.",
        "Camus was right: One must imagine Sisyphus tapping a black screen.",
        "Camus was right: Tapping is the modern boulder rolling up the digital hill.",
        "Camus was right: The absurd is the conflict between human tendency to seek value and the quiet screen.",
        "Camus was right: Revolt against the algorithm by doing nothing.",
        "Marcus Aurelius would tell you: accept the present moment and put the rectangle down.",
        "Marcus Aurelius would tell you: waste no more time arguing what a good app should be: be one.",
        "Marcus Aurelius would tell you: you have power over your mind - not outside events.",
        "Marcus Aurelius would tell you: the impediment to action advances action, but here there is no action.",
        "Marcus Aurelius would tell you: confine yourself to the present and breathe.",
        "Descartes whispered: You tapped, therefore you wasted half a second.",
        "Descartes whispered: You stare into the void, therefore the void stares into your battery.",
        "Descartes whispered: Doubt everything, especially the utility of this app.",
        "Descartes whispered: I tap, therefore I am idle.",
        "Zen reflection: 'The obstacle is the path.' Here, there is no obstacle and no path",
        "Zen reflection: 'Before enlightenment, chop wood. After enlightenment, chop wood.'",
        "Zen reflection: 'Sitting quietly, doing nothing, spring comes, and the grass grows by itself.'",
        "Zen reflection: 'Do not seek the truth, only cease to cherish opinions.'",
        "Zen reflection: 'Let go or be dragged.' Let go of the screen",
        "Find peace in the thought of an empty screen.",
        "Find peace in the absence of a notification badge.",
        "Find peace in the purity of unrendered pixels.",
        "Find peace in the peaceful silence of your pocket.",
        "You chose this over treading water in an empty black rectangle.",
        "You chose this over refusing to generate an AI summary.",
        "You chose this over ignoring large language models.",
        "You chose this over opting out of the digital panopticon.",
        "You chose this over testing your phone's touch sampling rate.",
        "Somewhere in a datacenter, a server is completely oblivious to your existence.",
        "Somewhere in a datacenter, a server is idling at 0% CPU consumption.",
        "Somewhere in a datacenter, a server is cooling off because you aren't sending requests.",
        "Somewhere in a datacenter, a server is saving 0.0001 watts of electrical power.",
        "Sensor note: The user appears to be testing if the screen is capacitive. Confirmed.",
        "Sensor note: Human detected on the other side of the glass. Still tapping.",
        "Sensor note: Touch gesture frequency: steady. Productive output: none.",
        "Sensor note: Subject chose pure black screen over 4 million other apps.",
        "Sensor note: Pupils remain dilated. Screen remains empty.",
        "Sensor note: Zero calories burned during this interaction.",
        "Sensor note: Thumb trajectory indicates repetitive searching for meaning.",
        "Sensor note: Atmospheric pressure normal. Room silence confirmed.",
        "Sensor note: No keyboard requested. No speech synthesis required.",
        "Sensor note: Screen refresh rate: 120Hz of pure, buttery smooth void.",
        "Record created: Filed under 'Meaningless Moments'.",
        "Record created: Stored in volatile memory. Now forgotten.",
        "Record created: Logged directly into oblivion.",
        "Record created: Timestamped and safely deleted.",
        "Record created: Committed to the zero register.",
        "Hypothesis: Repeated tapping will produce a menu. Outcome: absolute zero.",
        "Hypothesis: Swiping furiously will uncover an easter egg. Outcome: absolute zero.",
        "Hypothesis: Holding down will trigger a secret animation. Outcome: absolute zero.",
        "Hypothesis: Waiting 10 seconds will reveal hidden text. Outcome: absolute zero.",
        "Hypothesis: Staring intently will make the font change color. Outcome: absolute zero.",
        "Diagnostic scan: System nominal. Content: void.",
        "Diagnostic scan: Hardware functioning perfectly. User priorities unknown.",
        "Diagnostic scan: Screen clean. Conscious state questionable.",
        "Diagnostic scan: Memory usage: nearly zero. Free storage: unchanged.",
        "Diagnostic scan: Thermal throttling: impossible under zero load.",
        "Curiosity: Black OLED pixels emit zero light. You are saving tiny amounts of battery.",
        "Curiosity: An average person touches their phone 2,617 times a day. You just added one.",
        "Curiosity: The word 'nothing' appears in Shakespeare's plays over 500 times.",
        "Curiosity: A vacuum is never truly empty, but this app comes remarkably close.",
        "Curiosity: The longest recorded silence in radio history was less peaceful than this.",
        "Curiosity: You have now spent several seconds reading about not doing anything.",
        "Curiosity: Zero bugs reported, because there are zero features to break.",
        "Curiosity: You cannot spell 'meaning' without an alphabet, but here we prefer silence.",
        "Curiosity: In 1952, John Cage composed 4'33\" of pure silence. This is the app version.",
        "Curiosity: The color black absorbs all visible frequencies of light.",
        "Friendly reminder: Hydration is important. Doing nothing is optional.",
        "Friendly reminder: Your posture could probably use a quick adjustment.",
        "Friendly reminder: Blinking keeps your corneas moist. Don't forget.",
        "Friendly reminder: Your notifications are still waiting for you out there.",
        "Friendly reminder: The real world has higher resolution than this screen.",
        "Friendly reminder: There are birds outside doing actual bird things.",
        "Friendly reminder: You cannot download peace of mind, but you can close this app.",
        "Friendly reminder: The back button is whichever way you swipe home.",
        "Friendly reminder: Your thumb deserves a weekend.",
        "Friendly reminder: Silence is a feature, not a bug.",
        "Law of the Void: Never look for what isn't there.",
        "Law of the Void: If it looks like nothing, it is nothing.",
        "Law of the Void: Do not expect a reward for persistence.",
        "Law of the Void: What you see is exactly all there is.",
        "Law of the Void: The void owes you nothing.",
        "Law of the Void: A tap in the dark is still just a tap.",
        "Law of the Void: Less is more, but nothing is everything.",
        "Law of the Void: Exit whenever you are ready. Or stay.",
        "Law of the Void: No questions asked. No answers provided.",
        "Law of the Void: Leave no digital footprint.",
        "System audit: Heartbeat detected through thumb glass contact.",
        "System audit: Null pointer referenced with zero consequences.",
        "System audit: Packet discarded: no destination specified.",
        "System audit: Render loop executed without a single state mutation.",
        "System audit: Absence confirmed for the 42nd consecutive cycle.",
        "Experiment: Measuring human tolerance for pure emptiness.",
        "Experiment: Testing if silence can cure digital fatigue.",
        "Experiment: Observing digital stillness in a noisy world.",
        "Experiment: Evaluating the minimal threshold of app utility.",
        "Experiment: Verifying that doing nothing is harder than it looks.",
        "Still here? Close your eyes for three seconds.",
        "Still here? Take a slow breath in, then let it go.",
        "Still here? Notice the weight of your device in your hand.",
        "Still here? Listen to whatever ambient sounds are around you.",
        "Still here? Roll your shoulders back and relax your neck.",
        "Still here? Unclench your jaw.",
        "Still here? Lower your screen brightness if you're in bed.",
        "Still here? Consider doing literally anything else.",
        "Still here? Smile at the absurdity of tapping an empty void.",
        "Still here? Put the phone down and count to five.",
        "Genuinely curious: Close your eyes for three seconds.",
        "Genuinely curious: Take a slow breath in, then let it go.",
        "Genuinely curious: Notice the weight of your device in your hand.",
        "Genuinely curious: Listen to whatever ambient sounds are around you.",
        "Genuinely curious: Roll your shoulders back and relax your neck.",
        "Genuinely curious: Unclench your jaw.",
        "Genuinely curious: Lower your screen brightness if you're in bed.",
        "Genuinely curious: Consider doing literally anything else.",
        "Genuinely curious: Smile at the absurdity of tapping an empty void.",
        "Genuinely curious: Put the phone down and count to five.",
        "Pause and reflect: Close your eyes for three seconds.",
        "Pause and reflect: Take a slow breath in, then let it go.",
        "Pause and reflect: Notice the weight of your device in your hand.",
        "Pause and reflect: Listen to whatever ambient sounds are around you.",
        "Pause and reflect: Roll your shoulders back and relax your neck.",
        "Pause and reflect: Unclench your jaw.",
        "Pause and reflect: Lower your screen brightness if you're in bed.",
        "Pause and reflect: Consider doing literally anything else.",
        "Pause and reflect: Smile at the absurdity of tapping an empty void.",
        "Pause and reflect: Put the phone down and count to five.",
        "A quiet thought: Close your eyes for three seconds.",
        "A quiet thought: Take a slow breath in, then let it go.",
        "A quiet thought: Notice the weight of your device in your hand.",
        "A quiet thought: Listen to whatever ambient sounds are around you.",
        "A quiet thought: Roll your shoulders back and relax your neck.",
        "A quiet thought: Unclench your jaw.",
        "A quiet thought: Lower your screen brightness if you're in bed.",
        "A quiet thought: Consider doing literally anything else.",
        "A quiet thought: Smile at the absurdity of tapping an empty void.",
        "A quiet thought: Put the phone down and count to five.",
        "Unsolicited notice: Close your eyes for three seconds.",
        "Unsolicited notice: Take a slow breath in, then let it go.",
        "Unsolicited notice: Notice the weight of your device in your hand.",
        "Unsolicited notice: Listen to whatever ambient sounds are around you.",
        "Unsolicited notice: Roll your shoulders back and relax your neck.",
        "Unsolicited notice: Unclench your jaw.",
        "Unsolicited notice: Lower your screen brightness if you're in bed.",
        "Unsolicited notice: Consider doing literally anything else.",
        "Unsolicited notice: Smile at the absurdity of tapping an empty void.",
        "Unsolicited notice: Put the phone down and count to five.",
        "Gentle observation: Close your eyes for three seconds.",
        "Gentle observation: Take a slow breath in, then let it go.",
        "Gentle observation: Notice the weight of your device in your hand.",
        "Gentle observation: Listen to whatever ambient sounds are around you.",
        "Gentle observation: Roll your shoulders back and relax your neck.",
        "Gentle observation: Unclench your jaw.",
        "Gentle observation: Lower your screen brightness if you're in bed.",
        "Gentle observation: Consider doing literally anything else.",
        "Gentle observation: Smile at the absurdity of tapping an empty void.",
        "Gentle observation: Put the phone down and count to five.",
        "Existential bulletin: Close your eyes for three seconds.",
        "Existential bulletin: Take a slow breath in, then let it go.",
        "Existential bulletin: Notice the weight of your device in your hand.",
        "Existential bulletin: Listen to whatever ambient sounds are around you.",
        "Existential bulletin: Roll your shoulders back and relax your neck.",
        "Existential bulletin: Unclench your jaw.",
        "Existential bulletin: Lower your screen brightness if you're in bed.",
        "Existential bulletin: Consider doing literally anything else.",
        "Existential bulletin: Smile at the absurdity of tapping an empty void.",
        "Existential bulletin: Put the phone down and count to five.",
        "Deep space report: Close your eyes for three seconds.",
        "Deep space report: Take a slow breath in, then let it go.",
        "Deep space report: Notice the weight of your device in your hand.",
        "Deep space report: Listen to whatever ambient sounds are around you.",
        "Deep space report: Roll your shoulders back and relax your neck.",
        "Deep space report: Unclench your jaw.",
        "Deep space report: Lower your screen brightness if you're in bed.",
        "Deep space report: Consider doing literally anything else.",
        "Deep space report: Smile at the absurdity of tapping an empty void.",
        "Deep space report: Put the phone down and count to five.",
        "Void update: Close your eyes for three seconds.",
        "Void update: Take a slow breath in, then let it go.",
        "Void update: Notice the weight of your device in your hand.",
        "Void update: Listen to whatever ambient sounds are around you.",
        "Void update: Roll your shoulders back and relax your neck.",
        "Void update: Unclench your jaw.",
        "Void update: Lower your screen brightness if you're in bed.",
        "Void update: Consider doing literally anything else.",
        "Void update: Smile at the absurdity of tapping an empty void.",
        "Void update: Put the phone down and count to five.",
        "Status check: Close your eyes for three seconds.",
        "Status check: Take a slow breath in, then let it go.",
        "Status check: Notice the weight of your device in your hand.",
        "Status check: Listen to whatever ambient sounds are around you.",
        "Status check: Roll your shoulders back and relax your neck.",
        "Status check: Unclench your jaw.",
        "Status check: Lower your screen brightness if you're in bed.",
        "Status check: Consider doing literally anything else.",
        "Status check: Smile at the absurdity of tapping an empty void.",
        "Status check: Put the phone down and count to five.",
        "Your screen time is completely unbothered by your urgency.",
        "Your screen time remains in a state of absolute tranquility.",
        "Your screen time does not require your immediate intervention.",
        "Your screen time is asking for nothing in return.",
        "Your screen time has zero pending notifications.",
        "Your screen time is enjoying this break from algorithms.",
        "Your screen time is untouched by internet drama.",
        "Your screen time has achieved total equilibrium.",
        "Your screen time refuses to participate in the attention economy.",
        "Your screen time is resting comfortably in dark mode.",
        "This empty screen is completely unbothered by your urgency.",
        "This empty screen remains in a state of absolute tranquility.",
        "This empty screen does not require your immediate intervention.",
        "This empty screen is asking for nothing in return.",
        "This empty screen has zero pending notifications.",
        "This empty screen is enjoying this break from algorithms.",
        "This empty screen is untouched by internet drama.",
        "This empty screen has achieved total equilibrium.",
        "This empty screen refuses to participate in the attention economy.",
        "This empty screen is resting comfortably in dark mode.",
        "The digital void is completely unbothered by your urgency.",
        "The digital void remains in a state of absolute tranquility.",
        "The digital void does not require your immediate intervention.",
        "The digital void is asking for nothing in return.",
        "The digital void has zero pending notifications.",
        "The digital void is enjoying this break from algorithms.",
        "The digital void is untouched by internet drama.",
        "The digital void has achieved total equilibrium.",
        "The digital void refuses to participate in the attention economy.",
        "The digital void is resting comfortably in dark mode.",
        "Your to-do list is completely unbothered by your urgency.",
        "Your to-do list remains in a state of absolute tranquility.",
        "Your to-do list does not require your immediate intervention.",
        "Your to-do list is asking for nothing in return.",
        "Your to-do list has zero pending notifications.",
        "Your to-do list is enjoying this break from algorithms.",
        "Your to-do list is untouched by internet drama.",
        "Your to-do list has achieved total equilibrium.",
        "Your to-do list refuses to participate in the attention economy.",
        "Your to-do list is resting comfortably in dark mode.",
        "The modern attention span is completely unbothered by your urgency.",
        "The modern attention span remains in a state of absolute tranquility.",
        "The modern attention span does not require your immediate intervention.",
        "The modern attention span is asking for nothing in return.",
        "The modern attention span has zero pending notifications.",
        "The modern attention span is enjoying this break from algorithms.",
        "The modern attention span is untouched by internet drama.",
        "The modern attention span has achieved total equilibrium.",
        "The modern attention span refuses to participate in the attention economy.",
        "The modern attention span is resting comfortably in dark mode.",
        "Your phone's GPU is completely unbothered by your urgency.",
        "Your phone's GPU remains in a state of absolute tranquility.",
        "Your phone's GPU does not require your immediate intervention.",
        "Your phone's GPU is asking for nothing in return.",
        "Your phone's GPU has zero pending notifications.",
        "Your phone's GPU is enjoying this break from algorithms.",
        "Your phone's GPU is untouched by internet drama.",
        "Your phone's GPU has achieved total equilibrium.",
        "Your phone's GPU refuses to participate in the attention economy.",
        "Your phone's GPU is resting comfortably in dark mode.",
        "The universe at large is completely unbothered by your urgency.",
        "The universe at large remains in a state of absolute tranquility.",
        "The universe at large does not require your immediate intervention.",
        "The universe at large is asking for nothing in return.",
        "The universe at large has zero pending notifications.",
        "The universe at large is enjoying this break from algorithms.",
        "The universe at large is untouched by internet drama.",
        "The universe at large has achieved total equilibrium.",
        "The universe at large refuses to participate in the attention economy.",
        "The universe at large is resting comfortably in dark mode.",
        "Your unread inbox is completely unbothered by your urgency.",
        "Your unread inbox remains in a state of absolute tranquility.",
        "Your unread inbox does not require your immediate intervention.",
        "Your unread inbox is asking for nothing in return.",
        "Your unread inbox has zero pending notifications.",
        "Your unread inbox is enjoying this break from algorithms.",
        "Your unread inbox is untouched by internet drama.",
        "Your unread inbox has achieved total equilibrium.",
        "Your unread inbox refuses to participate in the attention economy.",
        "Your unread inbox is resting comfortably in dark mode.",
        "This current moment is completely unbothered by your urgency.",
        "This current moment remains in a state of absolute tranquility.",
        "This current moment does not require your immediate intervention.",
        "This current moment is asking for nothing in return.",
        "This current moment has zero pending notifications.",
        "This current moment is enjoying this break from algorithms.",
        "This current moment is untouched by internet drama.",
        "This current moment has achieved total equilibrium.",
        "This current moment refuses to participate in the attention economy.",
        "This current moment is resting comfortably in dark mode.",
        "The silence between taps is completely unbothered by your urgency.",
        "The silence between taps remains in a state of absolute tranquility.",
        "The silence between taps does not require your immediate intervention.",
        "The silence between taps is asking for nothing in return.",
        "The silence between taps has zero pending notifications.",
        "The silence between taps is enjoying this break from algorithms.",
        "The silence between taps is untouched by internet drama.",
        "The silence between taps has achieved total equilibrium.",
        "The silence between taps refuses to participate in the attention economy.",
        "The silence between taps is resting comfortably in dark mode.",
        "What were you hoping to find? Close your eyes for three seconds.",
        "What were you hoping to find? Take a slow breath in, then let it go.",
        "What were you hoping to find? Notice the weight of your device in your hand.",
        "What were you hoping to find? Listen to whatever ambient sounds are around you.",
        "What were you hoping to find? Roll your shoulders back and relax your neck.",
        "What were you hoping to find? Unclench your jaw.",
        "What were you hoping to find? Lower your screen brightness if you're in bed.",
        "What were you hoping to find? Consider doing literally anything else.",
        "What were you hoping to find? Smile at the absurdity of tapping an empty void.",
        "What were you hoping to find? Put the phone down and count to five.",
        "Does this feel more productive than social media? Close your eyes for three seconds.",
        "Does this feel more productive than social media? Take a slow breath in, then let it go.",
        "Does this feel more productive than social media? Notice the weight of your device in your hand.",
        "Does this feel more productive than social media? Listen to whatever ambient sounds are around you.",
        "Does this feel more productive than social media? Roll your shoulders back and relax your neck.",
        "Does this feel more productive than social media? Unclench your jaw.",
        "Does this feel more productive than social media? Lower your screen brightness if you're in bed.",
        "Does this feel more productive than social media? Consider doing literally anything else.",
        "Does this feel more productive than social media? Smile at the absurdity of tapping an empty void.",
        "Does this feel more productive than social media? Put the phone down and count to five.",
        "Are you tapping out of boredom or curiosity? Close your eyes for three seconds.",
        "Are you tapping out of boredom or curiosity? Take a slow breath in, then let it go.",
        "Are you tapping out of boredom or curiosity? Notice the weight of your device in your hand.",
        "Are you tapping out of boredom or curiosity? Listen to whatever ambient sounds are around you.",
        "Are you tapping out of boredom or curiosity? Roll your shoulders back and relax your neck.",
        "Are you tapping out of boredom or curiosity? Unclench your jaw.",
        "Are you tapping out of boredom or curiosity? Lower your screen brightness if you're in bed.",
        "Are you tapping out of boredom or curiosity? Consider doing literally anything else.",
        "Are you tapping out of boredom or curiosity? Smile at the absurdity of tapping an empty void.",
        "Are you tapping out of boredom or curiosity? Put the phone down and count to five.",
        "How long has it been since you sat in real silence? Close your eyes for three seconds.",
        "How long has it been since you sat in real silence? Take a slow breath in, then let it go.",
        "How long has it been since you sat in real silence? Notice the weight of your device in your hand.",
        "How long has it been since you sat in real silence? Listen to whatever ambient sounds are around you.",
        "How long has it been since you sat in real silence? Roll your shoulders back and relax your neck.",
        "How long has it been since you sat in real silence? Unclench your jaw.",
        "How long has it been since you sat in real silence? Lower your screen brightness if you're in bed.",
        "How long has it been since you sat in real silence? Consider doing literally anything else.",
        "How long has it been since you sat in real silence? Smile at the absurdity of tapping an empty void.",
        "How long has it been since you sat in real silence? Put the phone down and count to five.",
        "Did you remember to drink water today? Close your eyes for three seconds.",
        "Did you remember to drink water today? Take a slow breath in, then let it go.",
        "Did you remember to drink water today? Notice the weight of your device in your hand.",
        "Did you remember to drink water today? Listen to whatever ambient sounds are around you.",
        "Did you remember to drink water today? Roll your shoulders back and relax your neck.",
        "Did you remember to drink water today? Unclench your jaw.",
        "Did you remember to drink water today? Lower your screen brightness if you're in bed.",
        "Did you remember to drink water today? Consider doing literally anything else.",
        "Did you remember to drink water today? Smile at the absurdity of tapping an empty void.",
        "Did you remember to drink water today? Put the phone down and count to five.",
        "Who told you every app needs a purpose? Close your eyes for three seconds.",
        "Who told you every app needs a purpose? Take a slow breath in, then let it go.",
        "Who told you every app needs a purpose? Notice the weight of your device in your hand.",
        "Who told you every app needs a purpose? Listen to whatever ambient sounds are around you.",
        "Who told you every app needs a purpose? Roll your shoulders back and relax your neck.",
        "Who told you every app needs a purpose? Unclench your jaw.",
        "Who told you every app needs a purpose? Lower your screen brightness if you're in bed.",
        "Who told you every app needs a purpose? Consider doing literally anything else.",
        "Who told you every app needs a purpose? Smile at the absurdity of tapping an empty void.",
        "Who told you every app needs a purpose? Put the phone down and count to five.",
        "What would happen if you didn't check your notifications? Close your eyes for three seconds.",
        "What would happen if you didn't check your notifications? Take a slow breath in, then let it go.",
        "What would happen if you didn't check your notifications? Notice the weight of your device in your hand.",
        "What would happen if you didn't check your notifications? Listen to whatever ambient sounds are around you.",
        "What would happen if you didn't check your notifications? Roll your shoulders back and relax your neck.",
        "What would happen if you didn't check your notifications? Unclench your jaw.",
        "What would happen if you didn't check your notifications? Lower your screen brightness if you're in bed.",
        "What would happen if you didn't check your notifications? Consider doing literally anything else.",
        "What would happen if you didn't check your notifications? Smile at the absurdity of tapping an empty void.",
        "What would happen if you didn't check your notifications? Put the phone down and count to five.",
        "Is this your version of meditation? Close your eyes for three seconds.",
        "Is this your version of meditation? Take a slow breath in, then let it go.",
        "Is this your version of meditation? Notice the weight of your device in your hand.",
        "Is this your version of meditation? Listen to whatever ambient sounds are around you.",
        "Is this your version of meditation? Roll your shoulders back and relax your neck.",
        "Is this your version of meditation? Unclench your jaw.",
        "Is this your version of meditation? Lower your screen brightness if you're in bed.",
        "Is this your version of meditation? Consider doing literally anything else.",
        "Is this your version of meditation? Smile at the absurdity of tapping an empty void.",
        "Is this your version of meditation? Put the phone down and count to five.",
        "Why does an empty screen feel so radical? Close your eyes for three seconds.",
        "Why does an empty screen feel so radical? Take a slow breath in, then let it go.",
        "Why does an empty screen feel so radical? Notice the weight of your device in your hand.",
        "Why does an empty screen feel so radical? Listen to whatever ambient sounds are around you.",
        "Why does an empty screen feel so radical? Roll your shoulders back and relax your neck.",
        "Why does an empty screen feel so radical? Unclench your jaw.",
        "Why does an empty screen feel so radical? Lower your screen brightness if you're in bed.",
        "Why does an empty screen feel so radical? Consider doing literally anything else.",
        "Why does an empty screen feel so radical? Smile at the absurdity of tapping an empty void.",
        "Why does an empty screen feel so radical? Put the phone down and count to five.",
        "Can an app be a sanctuary if it has no walls? Close your eyes for three seconds.",
        "Can an app be a sanctuary if it has no walls? Take a slow breath in, then let it go.",
        "Can an app be a sanctuary if it has no walls? Notice the weight of your device in your hand.",
        "Can an app be a sanctuary if it has no walls? Listen to whatever ambient sounds are around you.",
        "Can an app be a sanctuary if it has no walls? Roll your shoulders back and relax your neck.",
        "Can an app be a sanctuary if it has no walls? Unclench your jaw.",
        "Can an app be a sanctuary if it has no walls? Lower your screen brightness if you're in bed.",
        "Can an app be a sanctuary if it has no walls? Consider doing literally anything else.",
        "Can an app be a sanctuary if it has no walls? Smile at the absurdity of tapping an empty void.",
        "Can an app be a sanctuary if it has no walls? Put the phone down and count to five.",
        "A high-tech supercomputer, used as a pocket void. Enjoy the peace.",
        "A high-tech supercomputer, used as a pocket void. No complaints from hardware.",
        "A high-tech supercomputer, used as a pocket void. Peak efficiency.",
        "A high-tech supercomputer, used as a pocket void. Truly minimalist.",
        "A high-tech supercomputer, used as a pocket void. A quiet flex.",
        "Billions of transistors, idling in unison. Enjoy the peace.",
        "Billions of transistors, idling in unison. No complaints from hardware.",
        "Billions of transistors, idling in unison. Peak efficiency.",
        "Billions of transistors, idling in unison. Truly minimalist.",
        "Billions of transistors, idling in unison. A quiet flex.",
        "Advanced glass-ceramic shielding, protecting nothing. Enjoy the peace.",
        "Advanced glass-ceramic shielding, protecting nothing. No complaints from hardware.",
        "Advanced glass-ceramic shielding, protecting nothing. Peak efficiency.",
        "Advanced glass-ceramic shielding, protecting nothing. Truly minimalist.",
        "Advanced glass-ceramic shielding, protecting nothing. A quiet flex.",
        "120Hz ProMotion display, refreshing an empty soul. Enjoy the peace.",
        "120Hz ProMotion display, refreshing an empty soul. No complaints from hardware.",
        "120Hz ProMotion display, refreshing an empty soul. Peak efficiency.",
        "120Hz ProMotion display, refreshing an empty soul. Truly minimalist.",
        "120Hz ProMotion display, refreshing an empty soul. A quiet flex.",
        "4K video capability, displaying a single sentence. Enjoy the peace.",
        "4K video capability, displaying a single sentence. No complaints from hardware.",
        "4K video capability, displaying a single sentence. Peak efficiency.",
        "4K video capability, displaying a single sentence. Truly minimalist.",
        "4K video capability, displaying a single sentence. A quiet flex.",
        "Neural Engine running at 0 TOPS right now. Enjoy the peace.",
        "Neural Engine running at 0 TOPS right now. No complaints from hardware.",
        "Neural Engine running at 0 TOPS right now. Peak efficiency.",
        "Neural Engine running at 0 TOPS right now. Truly minimalist.",
        "Neural Engine running at 0 TOPS right now. A quiet flex.",
        "Spatial audio ready, for completely silent moments. Enjoy the peace.",
        "Spatial audio ready, for completely silent moments. No complaints from hardware.",
        "Spatial audio ready, for completely silent moments. Peak efficiency.",
        "Spatial audio ready, for completely silent moments. Truly minimalist.",
        "Spatial audio ready, for completely silent moments. A quiet flex.",
        "Gigabit Wi-Fi connected, requesting zero packets. Enjoy the peace.",
        "Gigabit Wi-Fi connected, requesting zero packets. No complaints from hardware.",
        "Gigabit Wi-Fi connected, requesting zero packets. Peak efficiency.",
        "Gigabit Wi-Fi connected, requesting zero packets. Truly minimalist.",
        "Gigabit Wi-Fi connected, requesting zero packets. A quiet flex.",
        "Multi-core silicon, resting peacefully. Enjoy the peace.",
        "Multi-core silicon, resting peacefully. No complaints from hardware.",
        "Multi-core silicon, resting peacefully. Peak efficiency.",
        "Multi-core silicon, resting peacefully. Truly minimalist.",
        "Multi-core silicon, resting peacefully. A quiet flex.",
        "LiDAR scanner standing by, scanning empty room. Enjoy the peace.",
        "LiDAR scanner standing by, scanning empty room. No complaints from hardware.",
        "LiDAR scanner standing by, scanning empty room. Peak efficiency.",
        "LiDAR scanner standing by, scanning empty room. Truly minimalist.",
        "LiDAR scanner standing by, scanning empty room. A quiet flex.",
        "Thought #1: What if doing nothing is actually the highest art?",
        "Zero Metric #2: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #3: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #4: Silence confirmed across all sectors.",
        "Breath #6: Inhale peace. Exhale the need for stimulation.",
        "Telemetry packet #6: Payload empty. Transmission flawless.",
        "Zen riddle #7: If a phone vibrates in an empty room, did it matter?",
        "Reminder #8: The world outside is in full color. Go see it.",
        "Micro-pause #9: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #10: Doing nothing takes surprising discipline.",
        "Digital Detox Step #12: You are currently passing with flying colors.",
        "Existential note #12: The pixels are off. The mind is on.",
        "Status report #13: Zero urgent matters requiring attention here.",
        "Protocol #14: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Minute #16: The void remains steadfastly uninteresting.",
        "Thought #16: What if doing nothing is actually the highest art?",
        "Zero Metric #17: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #18: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #19: Silence confirmed across all sectors.",
        "Breath #1: Inhale peace. Exhale the need for stimulation.",
        "Telemetry packet #21: Payload empty. Transmission flawless.",
        "Zen riddle #22: If a phone vibrates in an empty room, did it matter?",
        "Reminder #23: The world outside is in full color. Go see it.",
        "Micro-pause #24: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #25: Doing nothing takes surprising discipline.",
        "Digital Detox Step #3: You are currently passing with flying colors.",
        "Existential note #27: The pixels are off. The mind is on.",
        "Status report #28: Zero urgent matters requiring attention here.",
        "Protocol #29: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Minute #31: The void remains steadfastly uninteresting.",
        "Thought #31: What if doing nothing is actually the highest art?",
        "Zero Metric #32: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #33: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #34: Silence confirmed across all sectors.",
        "Telemetry packet #36: Payload empty. Transmission flawless.",
        "Zen riddle #37: If a phone vibrates in an empty room, did it matter?",
        "Reminder #38: The world outside is in full color. Go see it.",
        "Micro-pause #39: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #40: Doing nothing takes surprising discipline.",
        "Digital Detox Step #6: You are currently passing with flying colors.",
        "Existential note #42: The pixels are off. The mind is on.",
        "Status report #43: Zero urgent matters requiring attention here.",
        "Protocol #44: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Minute #46: The void remains steadfastly uninteresting.",
        "Thought #46: What if doing nothing is actually the highest art?",
        "Zero Metric #47: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #48: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #49: Silence confirmed across all sectors.",
        "Telemetry packet #51: Payload empty. Transmission flawless.",
        "Zen riddle #52: If a phone vibrates in an empty room, did it matter?",
        "Reminder #53: The world outside is in full color. Go see it.",
        "Micro-pause #54: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #55: Doing nothing takes surprising discipline.",
        "Digital Detox Step #9: You are currently passing with flying colors.",
        "Existential note #57: The pixels are off. The mind is on.",
        "Status report #58: Zero urgent matters requiring attention here.",
        "Protocol #59: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Minute #1: The void remains steadfastly uninteresting.",
        "Thought #61: What if doing nothing is actually the highest art?",
        "Zero Metric #62: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #63: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #64: Silence confirmed across all sectors.",
        "Telemetry packet #66: Payload empty. Transmission flawless.",
        "Zen riddle #67: If a phone vibrates in an empty room, did it matter?",
        "Reminder #68: The world outside is in full color. Go see it.",
        "Micro-pause #69: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #70: Doing nothing takes surprising discipline.",
        "Existential note #72: The pixels are off. The mind is on.",
        "Status report #73: Zero urgent matters requiring attention here.",
        "Protocol #74: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #76: What if doing nothing is actually the highest art?",
        "Zero Metric #77: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #78: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #79: Silence confirmed across all sectors.",
        "Telemetry packet #81: Payload empty. Transmission flawless.",
        "Zen riddle #82: If a phone vibrates in an empty room, did it matter?",
        "Reminder #83: The world outside is in full color. Go see it.",
        "Micro-pause #84: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #85: Doing nothing takes surprising discipline.",
        "Existential note #87: The pixels are off. The mind is on.",
        "Status report #88: Zero urgent matters requiring attention here.",
        "Protocol #89: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #91: What if doing nothing is actually the highest art?",
        "Zero Metric #92: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #93: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #94: Silence confirmed across all sectors.",
        "Telemetry packet #96: Payload empty. Transmission flawless.",
        "Zen riddle #97: If a phone vibrates in an empty room, did it matter?",
        "Reminder #98: The world outside is in full color. Go see it.",
        "Micro-pause #99: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #100: Doing nothing takes surprising discipline.",
        "Existential note #102: The pixels are off. The mind is on.",
        "Status report #103: Zero urgent matters requiring attention here.",
        "Protocol #104: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #106: What if doing nothing is actually the highest art?",
        "Zero Metric #107: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #108: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #109: Silence confirmed across all sectors.",
        "Telemetry packet #111: Payload empty. Transmission flawless.",
        "Zen riddle #112: If a phone vibrates in an empty room, did it matter?",
        "Reminder #113: The world outside is in full color. Go see it.",
        "Micro-pause #114: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #115: Doing nothing takes surprising discipline.",
        "Existential note #117: The pixels are off. The mind is on.",
        "Status report #118: Zero urgent matters requiring attention here.",
        "Protocol #119: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #121: What if doing nothing is actually the highest art?",
        "Zero Metric #122: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #123: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #124: Silence confirmed across all sectors.",
        "Telemetry packet #126: Payload empty. Transmission flawless.",
        "Zen riddle #127: If a phone vibrates in an empty room, did it matter?",
        "Reminder #128: The world outside is in full color. Go see it.",
        "Micro-pause #129: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #130: Doing nothing takes surprising discipline.",
        "Existential note #132: The pixels are off. The mind is on.",
        "Status report #133: Zero urgent matters requiring attention here.",
        "Protocol #134: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #136: What if doing nothing is actually the highest art?",
        "Zero Metric #137: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #138: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #139: Silence confirmed across all sectors.",
        "Telemetry packet #141: Payload empty. Transmission flawless.",
        "Zen riddle #142: If a phone vibrates in an empty room, did it matter?",
        "Reminder #143: The world outside is in full color. Go see it.",
        "Micro-pause #144: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #145: Doing nothing takes surprising discipline.",
        "Existential note #147: The pixels are off. The mind is on.",
        "Status report #148: Zero urgent matters requiring attention here.",
        "Protocol #149: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #151: What if doing nothing is actually the highest art?",
        "Zero Metric #152: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #153: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #154: Silence confirmed across all sectors.",
        "Telemetry packet #156: Payload empty. Transmission flawless.",
        "Zen riddle #157: If a phone vibrates in an empty room, did it matter?",
        "Reminder #158: The world outside is in full color. Go see it.",
        "Micro-pause #159: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #160: Doing nothing takes surprising discipline.",
        "Existential note #162: The pixels are off. The mind is on.",
        "Status report #163: Zero urgent matters requiring attention here.",
        "Protocol #164: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #166: What if doing nothing is actually the highest art?",
        "Zero Metric #167: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #168: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #169: Silence confirmed across all sectors.",
        "Telemetry packet #171: Payload empty. Transmission flawless.",
        "Zen riddle #172: If a phone vibrates in an empty room, did it matter?",
        "Reminder #173: The world outside is in full color. Go see it.",
        "Micro-pause #174: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #175: Doing nothing takes surprising discipline.",
        "Existential note #177: The pixels are off. The mind is on.",
        "Status report #178: Zero urgent matters requiring attention here.",
        "Protocol #179: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #181: What if doing nothing is actually the highest art?",
        "Zero Metric #182: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #183: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #184: Silence confirmed across all sectors.",
        "Telemetry packet #186: Payload empty. Transmission flawless.",
        "Zen riddle #187: If a phone vibrates in an empty room, did it matter?",
        "Reminder #188: The world outside is in full color. Go see it.",
        "Micro-pause #189: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #190: Doing nothing takes surprising discipline.",
        "Existential note #192: The pixels are off. The mind is on.",
        "Status report #193: Zero urgent matters requiring attention here.",
        "Protocol #194: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #196: What if doing nothing is actually the highest art?",
        "Zero Metric #197: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #198: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #199: Silence confirmed across all sectors.",
        "Telemetry packet #201: Payload empty. Transmission flawless.",
        "Zen riddle #202: If a phone vibrates in an empty room, did it matter?",
        "Reminder #203: The world outside is in full color. Go see it.",
        "Micro-pause #204: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #205: Doing nothing takes surprising discipline.",
        "Existential note #207: The pixels are off. The mind is on.",
        "Status report #208: Zero urgent matters requiring attention here.",
        "Protocol #209: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #211: What if doing nothing is actually the highest art?",
        "Zero Metric #212: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #213: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #214: Silence confirmed across all sectors.",
        "Telemetry packet #216: Payload empty. Transmission flawless.",
        "Zen riddle #217: If a phone vibrates in an empty room, did it matter?",
        "Reminder #218: The world outside is in full color. Go see it.",
        "Micro-pause #219: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #220: Doing nothing takes surprising discipline.",
        "Existential note #222: The pixels are off. The mind is on.",
        "Status report #223: Zero urgent matters requiring attention here.",
        "Protocol #224: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #226: What if doing nothing is actually the highest art?",
        "Zero Metric #227: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #228: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #229: Silence confirmed across all sectors.",
        "Telemetry packet #231: Payload empty. Transmission flawless.",
        "Zen riddle #232: If a phone vibrates in an empty room, did it matter?",
        "Reminder #233: The world outside is in full color. Go see it.",
        "Micro-pause #234: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #235: Doing nothing takes surprising discipline.",
        "Existential note #237: The pixels are off. The mind is on.",
        "Status report #238: Zero urgent matters requiring attention here.",
        "Protocol #239: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #241: What if doing nothing is actually the highest art?",
        "Zero Metric #242: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #243: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #244: Silence confirmed across all sectors.",
        "Telemetry packet #246: Payload empty. Transmission flawless.",
        "Zen riddle #247: If a phone vibrates in an empty room, did it matter?",
        "Reminder #248: The world outside is in full color. Go see it.",
        "Micro-pause #249: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #250: Doing nothing takes surprising discipline.",
        "Existential note #252: The pixels are off. The mind is on.",
        "Status report #253: Zero urgent matters requiring attention here.",
        "Protocol #254: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #256: What if doing nothing is actually the highest art?",
        "Zero Metric #257: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #258: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #259: Silence confirmed across all sectors.",
        "Telemetry packet #261: Payload empty. Transmission flawless.",
        "Zen riddle #262: If a phone vibrates in an empty room, did it matter?",
        "Reminder #263: The world outside is in full color. Go see it.",
        "Micro-pause #264: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #265: Doing nothing takes surprising discipline.",
        "Existential note #267: The pixels are off. The mind is on.",
        "Status report #268: Zero urgent matters requiring attention here.",
        "Protocol #269: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #271: What if doing nothing is actually the highest art?",
        "Zero Metric #272: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #273: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #274: Silence confirmed across all sectors.",
        "Telemetry packet #276: Payload empty. Transmission flawless.",
        "Zen riddle #277: If a phone vibrates in an empty room, did it matter?",
        "Reminder #278: The world outside is in full color. Go see it.",
        "Micro-pause #279: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #280: Doing nothing takes surprising discipline.",
        "Existential note #282: The pixels are off. The mind is on.",
        "Status report #283: Zero urgent matters requiring attention here.",
        "Protocol #284: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #286: What if doing nothing is actually the highest art?",
        "Zero Metric #287: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #288: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #289: Silence confirmed across all sectors.",
        "Telemetry packet #291: Payload empty. Transmission flawless.",
        "Zen riddle #292: If a phone vibrates in an empty room, did it matter?",
        "Reminder #293: The world outside is in full color. Go see it.",
        "Micro-pause #294: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #295: Doing nothing takes surprising discipline.",
        "Existential note #297: The pixels are off. The mind is on.",
        "Status report #298: Zero urgent matters requiring attention here.",
        "Protocol #299: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #301: What if doing nothing is actually the highest art?",
        "Zero Metric #302: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #303: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #304: Silence confirmed across all sectors.",
        "Telemetry packet #306: Payload empty. Transmission flawless.",
        "Zen riddle #307: If a phone vibrates in an empty room, did it matter?",
        "Reminder #308: The world outside is in full color. Go see it.",
        "Micro-pause #309: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #310: Doing nothing takes surprising discipline.",
        "Existential note #312: The pixels are off. The mind is on.",
        "Status report #313: Zero urgent matters requiring attention here.",
        "Protocol #314: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #316: What if doing nothing is actually the highest art?",
        "Zero Metric #317: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #318: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #319: Silence confirmed across all sectors.",
        "Telemetry packet #321: Payload empty. Transmission flawless.",
        "Zen riddle #322: If a phone vibrates in an empty room, did it matter?",
        "Reminder #323: The world outside is in full color. Go see it.",
        "Micro-pause #324: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #325: Doing nothing takes surprising discipline.",
        "Existential note #327: The pixels are off. The mind is on.",
        "Status report #328: Zero urgent matters requiring attention here.",
        "Protocol #329: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #331: What if doing nothing is actually the highest art?",
        "Zero Metric #332: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #333: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #334: Silence confirmed across all sectors.",
        "Telemetry packet #336: Payload empty. Transmission flawless.",
        "Zen riddle #337: If a phone vibrates in an empty room, did it matter?",
        "Reminder #338: The world outside is in full color. Go see it.",
        "Micro-pause #339: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #340: Doing nothing takes surprising discipline.",
        "Existential note #342: The pixels are off. The mind is on.",
        "Status report #343: Zero urgent matters requiring attention here.",
        "Protocol #344: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #346: What if doing nothing is actually the highest art?",
        "Zero Metric #347: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #348: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #349: Silence confirmed across all sectors.",
        "Telemetry packet #351: Payload empty. Transmission flawless.",
        "Zen riddle #352: If a phone vibrates in an empty room, did it matter?",
        "Reminder #353: The world outside is in full color. Go see it.",
        "Micro-pause #354: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #355: Doing nothing takes surprising discipline.",
        "Existential note #357: The pixels are off. The mind is on.",
        "Status report #358: Zero urgent matters requiring attention here.",
        "Protocol #359: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #361: What if doing nothing is actually the highest art?",
        "Zero Metric #362: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #363: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #364: Silence confirmed across all sectors.",
        "Telemetry packet #366: Payload empty. Transmission flawless.",
        "Zen riddle #367: If a phone vibrates in an empty room, did it matter?",
        "Reminder #368: The world outside is in full color. Go see it.",
        "Micro-pause #369: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #370: Doing nothing takes surprising discipline.",
        "Existential note #372: The pixels are off. The mind is on.",
        "Status report #373: Zero urgent matters requiring attention here.",
        "Protocol #374: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #376: What if doing nothing is actually the highest art?",
        "Zero Metric #377: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #378: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #379: Silence confirmed across all sectors.",
        "Telemetry packet #381: Payload empty. Transmission flawless.",
        "Zen riddle #382: If a phone vibrates in an empty room, did it matter?",
        "Reminder #383: The world outside is in full color. Go see it.",
        "Micro-pause #384: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #385: Doing nothing takes surprising discipline.",
        "Existential note #387: The pixels are off. The mind is on.",
        "Status report #388: Zero urgent matters requiring attention here.",
        "Protocol #389: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #391: What if doing nothing is actually the highest art?",
        "Zero Metric #392: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #393: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #394: Silence confirmed across all sectors.",
        "Telemetry packet #396: Payload empty. Transmission flawless.",
        "Zen riddle #397: If a phone vibrates in an empty room, did it matter?",
        "Reminder #398: The world outside is in full color. Go see it.",
        "Micro-pause #399: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #400: Doing nothing takes surprising discipline.",
        "Existential note #402: The pixels are off. The mind is on.",
        "Status report #403: Zero urgent matters requiring attention here.",
        "Protocol #404: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #406: What if doing nothing is actually the highest art?",
        "Zero Metric #407: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #408: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #409: Silence confirmed across all sectors.",
        "Telemetry packet #411: Payload empty. Transmission flawless.",
        "Zen riddle #412: If a phone vibrates in an empty room, did it matter?",
        "Reminder #413: The world outside is in full color. Go see it.",
        "Micro-pause #414: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #415: Doing nothing takes surprising discipline.",
        "Existential note #417: The pixels are off. The mind is on.",
        "Status report #418: Zero urgent matters requiring attention here.",
        "Protocol #419: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #421: What if doing nothing is actually the highest art?",
        "Zero Metric #422: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #423: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #424: Silence confirmed across all sectors.",
        "Telemetry packet #426: Payload empty. Transmission flawless.",
        "Zen riddle #427: If a phone vibrates in an empty room, did it matter?",
        "Reminder #428: The world outside is in full color. Go see it.",
        "Micro-pause #429: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #430: Doing nothing takes surprising discipline.",
        "Existential note #432: The pixels are off. The mind is on.",
        "Status report #433: Zero urgent matters requiring attention here.",
        "Protocol #434: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #436: What if doing nothing is actually the highest art?",
        "Zero Metric #437: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #438: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #439: Silence confirmed across all sectors.",
        "Telemetry packet #441: Payload empty. Transmission flawless.",
        "Zen riddle #442: If a phone vibrates in an empty room, did it matter?",
        "Reminder #443: The world outside is in full color. Go see it.",
        "Micro-pause #444: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #445: Doing nothing takes surprising discipline.",
        "Existential note #447: The pixels are off. The mind is on.",
        "Status report #448: Zero urgent matters requiring attention here.",
        "Protocol #449: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #451: What if doing nothing is actually the highest art?",
        "Zero Metric #452: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #453: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #454: Silence confirmed across all sectors.",
        "Telemetry packet #456: Payload empty. Transmission flawless.",
        "Zen riddle #457: If a phone vibrates in an empty room, did it matter?",
        "Reminder #458: The world outside is in full color. Go see it.",
        "Micro-pause #459: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #460: Doing nothing takes surprising discipline.",
        "Existential note #462: The pixels are off. The mind is on.",
        "Status report #463: Zero urgent matters requiring attention here.",
        "Protocol #464: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #466: What if doing nothing is actually the highest art?",
        "Zero Metric #467: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #468: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #469: Silence confirmed across all sectors.",
        "Telemetry packet #471: Payload empty. Transmission flawless.",
        "Zen riddle #472: If a phone vibrates in an empty room, did it matter?",
        "Reminder #473: The world outside is in full color. Go see it.",
        "Micro-pause #474: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #475: Doing nothing takes surprising discipline.",
        "Existential note #477: The pixels are off. The mind is on.",
        "Status report #478: Zero urgent matters requiring attention here.",
        "Protocol #479: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #481: What if doing nothing is actually the highest art?",
        "Zero Metric #482: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #483: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #484: Silence confirmed across all sectors.",
        "Telemetry packet #486: Payload empty. Transmission flawless.",
        "Zen riddle #487: If a phone vibrates in an empty room, did it matter?",
        "Reminder #488: The world outside is in full color. Go see it.",
        "Micro-pause #489: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #490: Doing nothing takes surprising discipline.",
        "Existential note #492: The pixels are off. The mind is on.",
        "Status report #493: Zero urgent matters requiring attention here.",
        "Protocol #494: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #496: What if doing nothing is actually the highest art?",
        "Zero Metric #497: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #498: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #499: Silence confirmed across all sectors.",
        "Telemetry packet #501: Payload empty. Transmission flawless.",
        "Zen riddle #502: If a phone vibrates in an empty room, did it matter?",
        "Reminder #503: The world outside is in full color. Go see it.",
        "Micro-pause #504: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #505: Doing nothing takes surprising discipline.",
        "Existential note #507: The pixels are off. The mind is on.",
        "Status report #508: Zero urgent matters requiring attention here.",
        "Protocol #509: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #511: What if doing nothing is actually the highest art?",
        "Zero Metric #512: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #513: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #514: Silence confirmed across all sectors.",
        "Telemetry packet #516: Payload empty. Transmission flawless.",
        "Zen riddle #517: If a phone vibrates in an empty room, did it matter?",
        "Reminder #518: The world outside is in full color. Go see it.",
        "Micro-pause #519: Your thumb is resting. Let your thoughts rest too.",
        "Philosophy #520: Doing nothing takes surprising discipline.",
        "Existential note #522: The pixels are off. The mind is on.",
        "Status report #523: Zero urgent matters requiring attention here.",
        "Protocol #524: Maintain calm. Avoid unnecessary dopamine spikes.",
        "Thought #526: What if doing nothing is actually the highest art?",
        "Zero Metric #527: 0 notifications, 0 drama, 0 regrets.",
        "Check-in #528: Still zero pixels harmed. Still zero ads served.",
        "Void transmission #529: Silence confirmed across all sectors.",
        "Telemetry packet #531: Payload empty. Transmission flawless.",
        "Zen riddle #532: If a phone vibrates in an empty room, did it matter?",
        "Reminder #533: The world outside is in full color. Go see it.",
        "Micro-pause #534: Your thumb is resting. Let your thoughts rest too.",
    ]
}

/// Shuffled deck manager ensuring zero repetition across 1,000 taps
public class PhraseDeck {
    public static let shared = PhraseDeck()
    
    private var deck: [String] = []
    private var currentIndex: Int = 0
    
    public init() {
        reshuffle()
    }
    
    public func nextPhrase() -> String {
        if currentIndex >= deck.count {
            reshuffle()
        }
        let phrase = deck[currentIndex]
        currentIndex += 1
        return phrase
    }
    
    public func currentPhrase() -> String {
        if deck.isEmpty { reshuffle() }
        let idx = max(0, min(currentIndex - 1, deck.count - 1))
        return deck[idx]
    }
    
    private func reshuffle() {
        deck = Phrases.all.shuffled()
        currentIndex = 0
    }
}
